// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{
  /////////////////////////////////////////////////////////////////////////////
  // Replace with your code 

  vec3 kd, ka , ks, l, kd_moon,v ;
  float p, noise ;

  kd = vec3(0.1, 0.1, 1.0) ;
  kd_moon = vec3(0.5,0.5,0.5) ;
  ka =  kd * 1.5 ;
  ks = vec3(1.0, 1.0, 1.0) ;
  p = 32.0 ;
 
  float theta = -0.5 * animation_seconds * M_PI;

  mat3 rr = mat3(cos(theta), 0, sin(theta),
              0 ,1 , 0, 
	     -sin(theta), 0, cos(theta)) ;
			  
  l = normalize(vec3(cos(theta),0.5,sin(theta))); 
  v = normalize(vec3(-view_pos_fs_in)) ;
  
  if (is_moon) {   
      color = blinn_phong(ka, kd_moon, ks, p, normalize(rr*normal_fs_in), v, l)  ;
   }
  else {
     color = blinn_phong(ka, kd, ks, p, normal_fs_in, v, l)  ;
  }

  // generate perlin noise
  noise = perlin_noise(view_pos_fs_in.xyz) ;
  noise = (noise + 1)/2 ;
  noise = sin(theta*noise);
  if (noise>0.5 )
      color = noise *color ;

  
  /////////////////////////////////////////////////////////////////////////////
}

